[package]
name = "basic-udev"
version = "0.1.1"
edition = "2021"
authors = ["Sean Cross <sean@xobs.io>"]
description = "A drop-in, pure-rust implementation of some udev features"
repository = "https://github.com/xobs/basic-udev"
license = "MIT OR Apache-2.0"
keywords = ["udev"]

[dependencies]
